import { mkdtemp, readFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

import { generateDiagramFile, generateDiagramSource } from '../../src/agent/generate.js'

describe('generateDiagramSource', () => {
  it('generates a signup flowchart from a plain-language request', () => {
    const result = generateDiagramSource({
      request: 'show the signup flow from landing page to email verification',
    })

    expect(result.diagramType).toBe('flowchart')
    expect(result.source).toContain('flowchart TD')
    expect(result.source).toContain('Landing page')
    expect(result.source).toContain('Email verified')
    expect(result.assumptions).toEqual([
      'No source context was provided; diagram is inferred from the request.',
    ])
  })

  it('chooses a sequence diagram for interaction requests', () => {
    const result = generateDiagramSource({
      request: 'show the interaction between browser and API',
    })

    expect(result.diagramType).toBe('sequence')
    expect(result.source).toContain('sequenceDiagram')
    expect(result.source).toContain('participant A as Browser')
    expect(result.source).toContain('participant B as API')
  })

  it('uses an explicitly requested diagram type', () => {
    const result = generateDiagramSource({
      request: 'show the support ticket lifecycle',
      type: 'state',
    })

    expect(result.diagramType).toBe('state')
    expect(result.source).toContain('stateDiagram-v2')
  })
})

describe('generateDiagramFile', () => {
  it('uses an injected diagram generation provider', async () => {
    const directory = await mkdtemp(join(tmpdir(), 'mermaid-agent-generate-'))
    const outputPath = join(directory, 'custom.mmd')
    const providerInputs: unknown[] = []

    const result = await generateDiagramFile(
      {
        request: 'show a custom flow',
        outputPath,
        type: 'flowchart',
      },
      {
        provider: {
          async generate(input) {
            providerInputs.push(input)
            return {
              diagramType: 'flowchart',
              assumptions: ['Generated by injected provider.'],
              source: 'flowchart TD\n  A --> B\n',
            }
          },
        },
        validateMermaidFile: async (path) => ({ ok: true, inputPath: path }),
      },
    )

    expect(providerInputs).toEqual([
      {
        request: 'show a custom flow',
        type: 'flowchart',
      },
    ])
    expect(result).toMatchObject({
      ok: true,
      outputPath,
      assumptions: ['Generated by injected provider.'],
    })
    await expect(readFile(outputPath, 'utf8')).resolves.toBe('flowchart TD\n  A --> B\n')
  })

  it('writes and validates a generated Mermaid file', async () => {
    const directory = await mkdtemp(join(tmpdir(), 'mermaid-agent-generate-'))
    const outputPath = join(directory, 'signup-flow.mmd')
    const validatedPaths: string[] = []

    const result = await generateDiagramFile(
      {
        request: 'show the signup flow from landing page to email verification',
        outputPath,
      },
      {
        validateMermaidFile: async (path) => {
          validatedPaths.push(path)
          return { ok: true, inputPath: path }
        },
      },
    )

    expect(result).toMatchObject({
      ok: true,
      outputPath,
      diagramType: 'flowchart',
    })
    expect(validatedPaths).toEqual([outputPath])
    await expect(readFile(outputPath, 'utf8')).resolves.toContain('Email verified')
  })

  it('returns provider generation errors', async () => {
    await expect(
      generateDiagramFile(
        {
          request: 'show the signup flow',
          outputPath: join(tmpdir(), 'provider-error.mmd'),
        },
        {
          provider: {
            async generate() {
              throw new Error('Provider is unavailable')
            },
          },
        },
      ),
    ).resolves.toEqual({
      ok: false,
      error: 'Failed to generate Mermaid source: Provider is unavailable',
    })
  })

  it('rejects an empty diagram request', async () => {
    await expect(
      generateDiagramFile({
        request: '   ',
        outputPath: join(tmpdir(), 'empty-request.mmd'),
      }),
    ).resolves.toEqual({
      ok: false,
      error: 'Diagram request is empty.',
    })
  })
})
